### ISSUE TITLE
Robot design: Kicker concept

### ISSUE THREAD

**Issue by grantkelly** [Tasignotas/SDP#12]
Kicker systems should be researched. Last year's examples may not help us much given how different their robots' dimensions are. Most had their kicker start from the vertical position, and just push out. 

The issue should be revisited and discussed before any kickers are actually implemented, and certainly before the robot is modified.

**Comment by maneshkap** [comment]
Got a few ideas for this, will discuss when we meet up sometime today.

**Comment by maneshkap** [comment]
This is one of the tests that a group in 2011 had done, since we are planning on basing robot actions using the vision I think it might be feasible to attach this at the front of the robot, we will however require a 3rd motor on it. This should give more power to the kicker rather than the flap like kicker that is seen in most examples.   Just an idea!

http://www.youtube.com/watch?v=uSrbk2a82Us

**Comment by rowanborder** [comment]
Looks good! Should be able to provide the perfect combination of power and accuracy. Can we start working on prototypes?

**Comment by Dimitrov-M** [comment]
I have started working on a prototype like the rubber band kicker
yesterday. I will try to finish it today and leave something to test with.

**Comment by easyCZ** [comment]
Could we get an update on the kicker? Thanks!

**Comment by Dimitrov-M** [comment]
Today I will finish a four wheel design with a kicker. It should be ready
for testing by the end of today.
