### ISSUE TITLE
VISION: Dynamic Calibration GUI

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#38]
Implementation of a dynamic GUI for real time calibration. Investigate some options - be it OpenCV, SimpleCV or Qt or anything else.

**Comment by victor-dumitrescu** [comment]
I'm starting to look into this now.

**Comment by victor-dumitrescu** [comment]
I have committed an initial implementation. The GUI runs alongside the vision system. The values that you set manually can be accessed in real-time through the config_file attribute of the calibration GUI, using its get_value(color, setting) method. 

For example, in the loop of the controller, this would be:
self.GUI.calibration_gui.config_file.get_value('yellow', 'UH')
This is all just provisional and can be changed to suit the actual needs of the vision system.

The GUI initializes with the yellow colour and you can use the keys 'b', 'r' and 'y' to change it. An 's' key saves the configuration to file in order to be retrieved when the system is started next time. Note that keys have to be held down, not simply typed. (I can't figure why this is the case for now.)

I will be away for the next 2 days so if anyone wants to work on this, feel free!

**Comment by easyCZ** [comment]
The first version has been pushed to origin.
