### ISSUE TITLE
VISION: Plate corner detection

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#42]
Attempt to use the shape of the plate to our advantage to predict the orientation based on the black dot and parallel lines of the plate.

**Comment by easyCZ** [comment]
[This](https://opencv-python-tutroals.readthedocs.org/en/latest/py_tutorials/py_feature2d/py_fast/py_fast.html#fast) might be relevant.

**Comment by easyCZ** [comment]
Or [this](https://opencv-python-tutroals.readthedocs.org/en/latest/py_tutorials/py_feature2d/py_shi_tomasi/py_shi_tomasi.html#shi-tomasi)

**Comment by grantkelly** [comment]
I know we don't _need_ to initialize where the robots are to use this type of detection. My question would be are we allowed to? i.e. Are the robots removed from the pitch at any time during the final? 

If we can initialize them manually, and they don't leave the pitch, anomalies in position and orientation will be _much_ easier to ignore, since the robots' size/shape won't change throughout the match. Especially so if used in combination with the geometry-based system you explained at the meeting. I will get an answer to my question as soon as I can.

Also, nice finds.

**Comment by easyCZ** [comment]
This would be quite unacceptable for any kind of testing we would want to do. It's way more convenient to not have to place the robot in one specific location. Not to mention the changes required when we change the robot design and make it different size.

**Comment by grantkelly** [comment]
It's not that we would have to place our or any other robot in a specific location. It's that we initiate it regardless of where it is placed before sending commands (for example by clicking the corners, like the pitch cropper).

I understand what you're saying, though, and modification so late before comms connect would probably be illegal, so I investigated it no further.

**Comment by easyCZ** [comment]
Can someone still look into this? Ideally we'd be able to detect with high precision the 4 corners of the plate. Thanks!

**Comment by easyCZ** [comment]
This could be used to get corners of the plate 
`rect = cv2.minAreaRect(cnt)`
`box = cv2.cv.BoxPoints(rect)`
`box = np.int0(box)`
`cv2.drawContours(im,[box],0,(0,0,255),2)`

**Comment by easyCZ** [comment]
I present to you very precise and stable angle tracking. The yellow line is the direction line.

![screenshot from 2014-02-25 14 14 03](https://f.cloud.github.com/assets/1419286/2258326/5672b1ee-9e27-11e3-8aef-640b736b21ae.png)

**Comment by macwai1** [comment]
Awesome. That's the last of our problems in vision.
