### ISSUE TITLE
PLANNING: Structure Proposal

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#67]
I was thinking about the organization of the planner and I came with something that could work. The idea is the following:

We have the Planner which is divided into Tactics. A tactic is executed when certain conditions of the pitch are full filled or partially fulfilled. Esssentially, we'd be able to score different tactics based on the current setting. The scoring would work in the following way - We have the ideal setup for each tactic and we take the movement changes required for to get to the ideal setting for each of them. We pick the best based on scores and attempt to move into that ideal position. If the opponent reacts to it we can still execute different tactics since it may score better in that setting.

What do you think? Would it work?

**Comment by Tasignotas** [comment]
It could work, but at the moment I'm trying to write a plan so that our robot could just grab the ball. I think that once we are able to go to the ball, grab it, pass it to the attacker and shoot it in a more or less reliable way, we should definitely look into having different sorts of tactics, but at this stage it's just too soon to start doing this.
